### ISSUE TITLE
Registry credential should be passed to check-operator step when running via ci pipeline

### ISSUE THREAD

**Issue by jinhli** [redhat-openshift-ecosystem/operator-pipelines#276]
## Bug Description
If partner use a private container registry to save the bundle image and bundle image index, credential  has been added to the cluster as a secret. But when the tool running "preflight check operator $(params.bundle_image) ", the image could not be pulled with the error "Error: failed to pull remote container: GET https://quay.io/v2/mayurwaghmode111/power-cloud-native-postgresql/manifests/1.12.0: UNAUTHORIZED: access to the requested resource is not authorized;"

## Version and Command Invocation
preflight check operator $(params.bundle_image)

## Expected Result
The  image could be pulled

## Actual Result
The image could not be pulled. Partner need to set the repository as public to move ahead

## Additional Context
[operator-ci-pipeline-run-fb6hn.log](https://github.com/redhat-openshift-ecosystem/openshift-preflight/files/8221422/operator-ci-pipeline-run-fb6hn.log)

**Comment by acornett21** [comment]
@jinhli It looks like this was resolved with the latest release of preflight, and subsequent update to the `preflight` task in this repo, see below for another partners testing results.
- redhat-openshift-ecosystem/openshift-preflight#610
