### ISSUE TITLE
incorrect image in ansible/roles/operator-pipeline/templates/openshift/tasks/digest-pinning.yml

### ISSUE THREAD

**Issue by dtrawins** [redhat-openshift-ecosystem/operator-pipelines#294]
Image quay.io/redhat-isv/digest-pinning-tool@sha256:42cb3b1b668b19ea656679a5d53b46ecf1ed14f42c48cc721ebdf72594ef3447 doesn't exist in the quay repository.
Probably it should be swapped by sha256:21cb7af396031d03b601d65e5600acdbd71dfe46a11dedd55b9a2abc507c6bee

**Comment by Allda** [comment]
The latest release of the pipeline uses quay.io/redhat-isv/digest-pinning-tool@sha256:7e9dd84000e597e5591d94e791e7c0be1f1efe7e60ab915b200c5c0dff2fa6ba which is available in the Quay repository.
