### ISSUE TITLE
Bundle version tag published in Catalog has extraneous "-1" appended

### ISSUE THREAD

**Issue by jfrancin** [redhat-openshift-ecosystem/operator-pipelines#295]
It would appear that every single operator bundle catalog entry shows an incorrect tag. 

Catalog cards for bundle images always show a "-1" appended to the tag, but that does not reflect either the actual Semantic Version in the bundle itself (as shown in the OperatorHub), or in the RHCC registry.

Here's an example:

For bundle product Aarna Networks Multi Cluster Orchestration Platform:
https://catalog.redhat.com/software/containers/aarna/amcop/61bca6fe9618481e52db085c

The catalog page above shows tag 1.0.2-1.
However, 1.0.2-1 cannot be found in RHCC:

```
$ skopeo inspect docker://registry.connect.redhat.com/aarna/amcop:1.0.2-1
FATA[0000] Error parsing image name "docker://registry.connect.redhat.com/aarna/amcop:1.0.2-1": reading manifest 1.0.2-1 in registry.connect.redhat.com/aarna/amcop: manifest unknown: manifest unknown 
```
But 1.0.2 can:

```
$ skopeo inspect docker://registry.connect.redhat.com/aarna/amcop:1.0.2
{
    "Name": "registry.connect.redhat.com/aarna/amcop",
    "Digest": "sha256:59c7ea92dc631b6c01d5b87c53612f75e90ce1f2584020bbc9dded5a447cda07",
    "RepoTags": [
        "1.0.1",
        "1.0.2",
        "latest"
[...]
```

And the same for _every other bundle published since the new bundle cert went in._

**Comment by maveric-tellrv** [comment]
@jfrancin one similar issue was fixed in [ISV-1857] Not sure if it still exists in Prod env.

**Comment by Allda** [comment]
@jfrancin This is already fixed as part of this pull request: https://github.com/redhat-openshift-ecosystem/operator-pipelines/pull/289
