### ISSUE TITLE
reserve-operator-name task needs to check for whether project has a different name already reserved

### ISSUE THREAD

**Issue by jfrancin** [redhat-openshift-ecosystem/operator-pipelines#347]
In ISVISSUE-217, we had a situation where the reserve-operator-name task died due to a duplicate-key error. 

The task wisely checks to see if the requested new operator package name is already reserved in Pyxis.

However, it does _not_ check to see if the project in question already has a **different** package name already reserved. Because it doesn't check ahead of time, the request to reserve the operator name blows up with a traceback due to the existing name.

Fix here would be to not only check for whether the new operator name to be reserved is already in use, but also to see if the **project** already has a different name assigned.

**Comment by mantomas** [comment]
WIP #401
