### ISSUE TITLE
CI-Pipeline permission denied failure on Azure and CRC

### ISSUE THREAD

**Issue by jsm84** [redhat-openshift-ecosystem/operator-pipelines#387]
This issue is explained in RH Jira ISV-2654, which I'd already tried resolving unsuccessfully in #366.

The ci-pipeline fails during the `generate-index : inspect-base-index` step when run on both CRC and Azure, with the following error:

```
+ tee -a podman-inspect.json
+ podman image inspect image-registry.openshift-image-registry.svc:5000/rvtest/certified-operator-index:v4.11
tee: podman-inspect.json: Permission denied
```

The root cause is that `podman-inspect.json` has `gid 0` (root group) ownership, but the `inspect-base-index` pod does not run with `gid 0` on either CRC or Azure. When `uid/gid 1000` attempts to write to this file, it fails as expected due to lacking permissions.

**Comment by mjturek** [comment]
I'm hitting this issue too on `ppc64le`, which requires using the `templates/crc-pod-template.yml` template. Is there any workaround?
