### ISSUE TITLE
[generate-index : inspect-base-index] Error: cannot set up namespace using "/usr/bin/newuidmap"

### ISSUE THREAD

**Issue by zcahana** [redhat-openshift-ecosystem/operator-pipelines#417]
When attempting to run the certification pipeline on a local OpenShift cluster (per [these instructions](https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.56/html/red_hat_software_certification_workflow_guide/assembly-running-the-certification-suite-locally_openshift-sw-cert-workflow-complete-pre-certification-checklist#proc_enabling-digest-pinning_openshift-sw-cert-workflow-installing-the-openshift-operator-pipeline)), I've hit the following errors (and related warnings):

```
[build-bundle : push] Pushing image-registry.openshift-image-registry.svc:5000/oco/redis-enterprise-operator-cert-bundle:v6.2.18-41c
[build-bundle : push] time="2023-02-12T20:26:35Z" level=warning msg="Error running newgidmap: exit status 1: newgidmap: write to gid_map failed: Operation not permitted\n"
[build-bundle : push] time="2023-02-12T20:26:35Z" level=warning msg="Falling back to single mapping"
[build-bundle : push] time="2023-02-12T20:26:35Z" level=warning msg="Error running newuidmap: exit status 1: newuidmap: write to uid_map failed: Operation not permitted\n"
[build-bundle : push] time="2023-02-12T20:26:35Z" level=warning msg="Falling back to single mapping"
```

```
[generate-index : inspect-base-index] + podman pull image-registry.openshift-image-registry.svc:5000/oco/certified-operator-index:v4.11
[generate-index : inspect-base-index] time="2023-02-12T20:27:00Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
[generate-index : inspect-base-index] time="2023-02-12T20:27:00Z" level=error msg="running `/usr/bin/newuidmap 31 0 1000 1 1 10000 5000`: newuidmap: write to uid_map failed: Operation not permitted\n"
[generate-index : inspect-base-index] Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1

[generate-index : determine-index-format] 2023/02/12 20:27:00 Skipping step because a previous step failed

failed to get logs for task generate-index : container step-determine-index-format has failed  : [{"key":"StartedAt","value":"2023-02-12T20:27:00.323Z","type":3}]
```

~I've managed to workaround it by granting the `privilieged` SCC to the pipeline's service account (as found in the [developer guide](https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/281770e61c933b73f71241174d26862d9e03d075/docs/developer-guide.md?plain=1#L87) - not something I'd typically look at as a pipeline user):~

Using OpenShift 4.11 and Certification Pipeline 1.0.4.

**Comment by zcahana** [comment]
Managed to workaround this by switching to an OpenShift 4.10 cluster (with same configuration).

**Comment by Allda** [comment]
Hi @zcahana there is a paragraph in user documentation that describes a step of custom SCC to a pipeline service account : (21.4. Execute the OpenShift Operator pipeline) https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.69/html-single/red_hat_software_certification_workflow_guide/index#assembly-running-the-certification-suite-locally_openshift-sw-cert-workflow-complete-pre-certification-checklist

Please try that and let us know if it works. Considering the 4.10 is eol now I will close this issue. Feel free to reopen if you need anything else.
