### ISSUE TITLE
Migrate from `v1beta1` Tekton APIs to `v1` APIs

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-pipelines#540]
## Problem
`v1beta` API's have been deprecated for awhile now. Staying on deprecated APIs, is forcing dependent projects to use older libraries, which could contain CVE's and unknown.

## Solution
Migrate tekton `Tasks`, `Pipelines` and other applicable API's to `v1`.

- Blocks: redhat-openshift-ecosystem/operator-certification-operator#152

**Comment by sxd** [comment]
@acornett21 wow!! this will be awesome!! waiting for it! =)

**Comment by Allda** [comment]
I created internal tracker for the migration: https://issues.redhat.com/browse/ISV-4397

**Comment by acornett21** [comment]
@Allda @tomasbakk I see the PR #577 has been merged for this, when is this expected to be released so I can coordinate the OCO release? Thanks!

**Comment by Allda** [comment]
@acornett21 This change went to the stage today and will continue to production next week on Monday.
